# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.EmailField(max_length=254)),
                ('rcpt_to', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('email', models.BinaryField()),
                ('message_id', models.CharField(db_index=True, default=None, max_length=255, null=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Mailbox')),
            ],
        ),
    ]
