# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161031_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='startup',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Startup'),
            preserve_default=False,
        ),
    ]
