# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161103_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='message',
            name='mail_from_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
