# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170104_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relay_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='permission_mode',
            field=models.IntegerField(choices=[(0, 'Allow default'), (1, 'Deny default')], default=0),
        ),
    ]
