# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170116_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
