# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_startup_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BinaryField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Message')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
