# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 09:37
from __future__ import unicode_literals

from django.db import migrations

def migrate_messages(apps, schema_editor):
    Message = apps.get_model("app", "Message")
    MessageContent = apps.get_model("app", "MessageContent")

    for message in Message.objects.all():
        mc = MessageContent()
        mc.message = message
        mc.email = message.email
        mc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_messagecontent'),
    ]

    operations = [
        migrations.RunPython(migrate_messages)
    ]
