# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_migrate_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
    ]
