# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 10:55
from __future__ import unicode_literals

import gc
from django.db import migrations, models
import email

def migrate_messages(apps, schema_editor):
    Message = apps.get_model("app", "Message")

    i = 0

    for message in Message.objects.all():
        emailobj = email.message_from_string(message.messagecontent.email)
        emailheaders = dict(emailobj)

        message.in_reply_to = emailheaders.get("In-Reply-To")[:255]
        message.references = emailheaders.get("References")[:255]
        message.save()

        # This operation is very memory intensive, force the GC collection
        i += 1
        if i % 10:
            gc.collect()
            i = 0

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='in_reply_to',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='references',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.RunPython(migrate_messages)
    ]
