# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170309_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='in_reply_to',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='references',
            field=models.TextField(default=None, null=True),
        ),
    ]
